// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Blowfish_Encrypt (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        plaintext_address0,
        plaintext_ce0,
        plaintext_q0,
        plaintext_address1,
        plaintext_ce1,
        plaintext_q1,
        ciphertext_address0,
        ciphertext_ce0,
        ciphertext_we0,
        ciphertext_d0,
        ciphertext_address1,
        ciphertext_ce1,
        ciphertext_we1,
        ciphertext_d1
);

parameter    ap_ST_fsm_state1 = 12'd1;
parameter    ap_ST_fsm_state2 = 12'd2;
parameter    ap_ST_fsm_state3 = 12'd4;
parameter    ap_ST_fsm_state4 = 12'd8;
parameter    ap_ST_fsm_state5 = 12'd16;
parameter    ap_ST_fsm_state6 = 12'd32;
parameter    ap_ST_fsm_state7 = 12'd64;
parameter    ap_ST_fsm_state8 = 12'd128;
parameter    ap_ST_fsm_state9 = 12'd256;
parameter    ap_ST_fsm_state10 = 12'd512;
parameter    ap_ST_fsm_state11 = 12'd1024;
parameter    ap_ST_fsm_state12 = 12'd2048;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [2:0] plaintext_address0;
output   plaintext_ce0;
input  [7:0] plaintext_q0;
output  [2:0] plaintext_address1;
output   plaintext_ce1;
input  [7:0] plaintext_q1;
output  [2:0] ciphertext_address0;
output   ciphertext_ce0;
output   ciphertext_we0;
output  [7:0] ciphertext_d0;
output  [2:0] ciphertext_address1;
output   ciphertext_ce1;
output   ciphertext_we1;
output  [7:0] ciphertext_d1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[2:0] plaintext_address0;
reg plaintext_ce0;
reg[2:0] plaintext_address1;
reg plaintext_ce1;
reg[2:0] ciphertext_address0;
reg ciphertext_ce0;
reg ciphertext_we0;
reg[7:0] ciphertext_d0;
reg[2:0] ciphertext_address1;
reg ciphertext_ce1;
reg ciphertext_we1;
reg[7:0] ciphertext_d1;

(* fsm_encoding = "none" *) reg   [11:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [4:0] P_address0;
reg    P_ce0;
wire   [31:0] P_q0;
wire   [7:0] S_0_address0;
reg    S_0_ce0;
wire   [31:0] S_0_q0;
wire   [7:0] S_1_address0;
reg    S_1_ce0;
wire   [31:0] S_1_q0;
wire   [7:0] S_2_address0;
reg    S_2_ce0;
wire   [31:0] S_2_q0;
wire   [7:0] S_3_address0;
reg    S_3_ce0;
wire   [31:0] S_3_q0;
reg   [7:0] plaintext_load_reg_624;
wire    ap_CS_fsm_state2;
reg   [7:0] plaintext_load_1_reg_629;
reg   [7:0] plaintext_load_2_reg_644;
wire    ap_CS_fsm_state3;
reg   [7:0] plaintext_load_3_reg_649;
reg   [7:0] plaintext_load_4_reg_664;
wire    ap_CS_fsm_state4;
reg   [7:0] plaintext_load_5_reg_669;
wire   [31:0] left_fu_336_p5;
wire    ap_CS_fsm_state5;
wire   [31:0] right_1_fu_344_p5;
wire   [4:0] i_fu_360_p2;
reg   [4:0] i_reg_697;
wire    ap_CS_fsm_state6;
wire   [0:0] icmp_ln76_fu_354_p2;
wire   [31:0] left_4_fu_429_p2;
reg   [31:0] left_4_reg_707;
wire    ap_CS_fsm_state7;
wire   [31:0] add_ln140_1_fu_515_p2;
reg   [31:0] add_ln140_1_reg_732;
wire    ap_CS_fsm_state8;
wire   [31:0] right_fu_521_p2;
wire    ap_CS_fsm_state9;
wire   [7:0] trunc_ln82_fu_554_p1;
reg   [7:0] trunc_ln82_reg_742;
wire    ap_CS_fsm_state11;
reg   [7:0] trunc_ln268_1_reg_747;
reg   [31:0] left_1_reg_305;
reg   [31:0] right_2_reg_315;
reg   [4:0] i_0_reg_325;
wire   [63:0] zext_ln77_fu_366_p1;
wire   [63:0] zext_ln140_fu_483_p1;
wire   [63:0] zext_ln140_1_fu_488_p1;
wire   [63:0] zext_ln140_2_fu_493_p1;
wire   [63:0] zext_ln140_3_fu_498_p1;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state12;
wire   [7:0] xor_ln262_fu_381_p2;
wire   [7:0] xor_ln263_fu_398_p2;
wire   [7:0] xor_ln264_fu_540_p2;
wire   [7:0] xor_ln265_fu_547_p2;
wire   [7:0] xor_ln266_fu_568_p2;
wire   [7:0] xor_ln267_fu_585_p2;
wire   [7:0] xor_ln268_fu_602_p2;
wire   [7:0] xor_ln269_fu_608_p2;
wire   [7:0] trunc_ln262_1_fu_371_p4;
wire   [7:0] trunc_ln263_1_fu_388_p4;
wire   [15:0] trunc_ln77_6_fu_425_p1;
wire   [15:0] trunc_ln77_5_fu_421_p1;
wire   [23:0] trunc_ln77_4_fu_417_p1;
wire   [23:0] trunc_ln77_3_fu_413_p1;
wire   [23:0] xor_ln77_2_fu_441_p2;
wire   [15:0] xor_ln77_1_fu_435_p2;
wire   [7:0] trunc_ln77_2_fu_409_p1;
wire   [7:0] trunc_ln77_fu_405_p1;
wire   [7:0] a_fu_447_p4;
wire   [7:0] b_fu_457_p4;
wire   [7:0] c_fu_467_p4;
wire   [7:0] d_fu_477_p2;
wire   [31:0] add_ln140_fu_503_p2;
wire   [31:0] xor_ln140_fu_509_p2;
wire   [7:0] trunc_ln264_1_fu_530_p4;
wire   [7:0] trunc_ln83_fu_526_p1;
wire   [7:0] trunc_ln266_1_fu_558_p4;
wire   [7:0] trunc_ln267_1_fu_575_p4;
reg   [11:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 12'd1;
end

Blowfish_Encrypt_P #(
    .DataWidth( 32 ),
    .AddressRange( 18 ),
    .AddressWidth( 5 ))
P_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(P_address0),
    .ce0(P_ce0),
    .q0(P_q0)
);

Blowfish_Encrypt_bkb #(
    .DataWidth( 32 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
S_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(S_0_address0),
    .ce0(S_0_ce0),
    .q0(S_0_q0)
);

Blowfish_Encrypt_cud #(
    .DataWidth( 32 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
S_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(S_1_address0),
    .ce0(S_1_ce0),
    .q0(S_1_q0)
);

Blowfish_Encrypt_dEe #(
    .DataWidth( 32 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
S_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(S_2_address0),
    .ce0(S_2_ce0),
    .q0(S_2_q0)
);

Blowfish_Encrypt_eOg #(
    .DataWidth( 32 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
S_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(S_3_address0),
    .ce0(S_3_ce0),
    .q0(S_3_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        i_0_reg_325 <= i_reg_697;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        i_0_reg_325 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        left_1_reg_305 <= left_4_reg_707;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        left_1_reg_305 <= right_1_fu_344_p5;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        right_2_reg_315 <= right_fu_521_p2;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        right_2_reg_315 <= left_fu_336_p5;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        add_ln140_1_reg_732 <= add_ln140_1_fu_515_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        i_reg_697 <= i_fu_360_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        left_4_reg_707 <= left_4_fu_429_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        plaintext_load_1_reg_629 <= plaintext_q1;
        plaintext_load_reg_624 <= plaintext_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        plaintext_load_2_reg_644 <= plaintext_q0;
        plaintext_load_3_reg_649 <= plaintext_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        plaintext_load_4_reg_664 <= plaintext_q0;
        plaintext_load_5_reg_669 <= plaintext_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        trunc_ln268_1_reg_747 <= {{right_2_reg_315[15:8]}};
        trunc_ln82_reg_742 <= trunc_ln82_fu_554_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        P_ce0 = 1'b1;
    end else begin
        P_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        S_0_ce0 = 1'b1;
    end else begin
        S_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        S_1_ce0 = 1'b1;
    end else begin
        S_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        S_2_ce0 = 1'b1;
    end else begin
        S_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        S_3_ce0 = 1'b1;
    end else begin
        S_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        ciphertext_address0 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        ciphertext_address0 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        ciphertext_address0 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        ciphertext_address0 = 64'd0;
    end else begin
        ciphertext_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        ciphertext_address1 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        ciphertext_address1 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        ciphertext_address1 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        ciphertext_address1 = 64'd1;
    end else begin
        ciphertext_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state6))) begin
        ciphertext_ce0 = 1'b1;
    end else begin
        ciphertext_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state6))) begin
        ciphertext_ce1 = 1'b1;
    end else begin
        ciphertext_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        ciphertext_d0 = xor_ln268_fu_602_p2;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        ciphertext_d0 = xor_ln266_fu_568_p2;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        ciphertext_d0 = xor_ln264_fu_540_p2;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        ciphertext_d0 = xor_ln262_fu_381_p2;
    end else begin
        ciphertext_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        ciphertext_d1 = xor_ln269_fu_608_p2;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        ciphertext_d1 = xor_ln267_fu_585_p2;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        ciphertext_d1 = xor_ln265_fu_547_p2;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        ciphertext_d1 = xor_ln263_fu_398_p2;
    end else begin
        ciphertext_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state11) | ((1'b1 == ap_CS_fsm_state6) & (icmp_ln76_fu_354_p2 == 1'd1)))) begin
        ciphertext_we0 = 1'b1;
    end else begin
        ciphertext_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state11) | ((1'b1 == ap_CS_fsm_state6) & (icmp_ln76_fu_354_p2 == 1'd1)))) begin
        ciphertext_we1 = 1'b1;
    end else begin
        ciphertext_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        plaintext_address0 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        plaintext_address0 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        plaintext_address0 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        plaintext_address0 = 64'd0;
    end else begin
        plaintext_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        plaintext_address1 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        plaintext_address1 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        plaintext_address1 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        plaintext_address1 = 64'd1;
    end else begin
        plaintext_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        plaintext_ce0 = 1'b1;
    end else begin
        plaintext_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        plaintext_ce1 = 1'b1;
    end else begin
        plaintext_ce1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln76_fu_354_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign P_address0 = zext_ln77_fu_366_p1;

assign S_0_address0 = zext_ln140_fu_483_p1;

assign S_1_address0 = zext_ln140_1_fu_488_p1;

assign S_2_address0 = zext_ln140_2_fu_493_p1;

assign S_3_address0 = zext_ln140_3_fu_498_p1;

assign a_fu_447_p4 = {{left_4_fu_429_p2[31:24]}};

assign add_ln140_1_fu_515_p2 = (S_3_q0 + xor_ln140_fu_509_p2);

assign add_ln140_fu_503_p2 = (S_0_q0 + S_1_q0);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign b_fu_457_p4 = {{xor_ln77_2_fu_441_p2[23:16]}};

assign c_fu_467_p4 = {{xor_ln77_1_fu_435_p2[15:8]}};

assign d_fu_477_p2 = (trunc_ln77_fu_405_p1 ^ trunc_ln77_2_fu_409_p1);

assign i_fu_360_p2 = (i_0_reg_325 + 5'd1);

assign icmp_ln76_fu_354_p2 = ((i_0_reg_325 == 5'd16) ? 1'b1 : 1'b0);

assign left_4_fu_429_p2 = (right_2_reg_315 ^ P_q0);

assign left_fu_336_p5 = {{{{plaintext_load_reg_624}, {plaintext_load_1_reg_629}}, {plaintext_load_2_reg_644}}, {plaintext_load_3_reg_649}};

assign right_1_fu_344_p5 = {{{{plaintext_load_4_reg_664}, {plaintext_load_5_reg_669}}, {plaintext_q0}}, {plaintext_q1}};

assign right_fu_521_p2 = (left_1_reg_305 ^ add_ln140_1_reg_732);

assign trunc_ln262_1_fu_371_p4 = {{left_1_reg_305[31:24]}};

assign trunc_ln263_1_fu_388_p4 = {{left_1_reg_305[23:16]}};

assign trunc_ln264_1_fu_530_p4 = {{left_1_reg_305[15:8]}};

assign trunc_ln266_1_fu_558_p4 = {{right_2_reg_315[31:24]}};

assign trunc_ln267_1_fu_575_p4 = {{right_2_reg_315[23:16]}};

assign trunc_ln77_2_fu_409_p1 = right_2_reg_315[7:0];

assign trunc_ln77_3_fu_413_p1 = right_2_reg_315[23:0];

assign trunc_ln77_4_fu_417_p1 = P_q0[23:0];

assign trunc_ln77_5_fu_421_p1 = right_2_reg_315[15:0];

assign trunc_ln77_6_fu_425_p1 = P_q0[15:0];

assign trunc_ln77_fu_405_p1 = P_q0[7:0];

assign trunc_ln82_fu_554_p1 = right_2_reg_315[7:0];

assign trunc_ln83_fu_526_p1 = left_1_reg_305[7:0];

assign xor_ln140_fu_509_p2 = (add_ln140_fu_503_p2 ^ S_2_q0);

assign xor_ln262_fu_381_p2 = (trunc_ln262_1_fu_371_p4 ^ 8'd105);

assign xor_ln263_fu_398_p2 = (trunc_ln263_1_fu_388_p4 ^ 8'd136);

assign xor_ln264_fu_540_p2 = (trunc_ln264_1_fu_530_p4 ^ 8'd195);

assign xor_ln265_fu_547_p2 = (trunc_ln83_fu_526_p1 ^ 8'd204);

assign xor_ln266_fu_568_p2 = (trunc_ln266_1_fu_558_p4 ^ 8'd159);

assign xor_ln267_fu_585_p2 = (trunc_ln267_1_fu_575_p4 ^ 8'd194);

assign xor_ln268_fu_602_p2 = (trunc_ln268_1_reg_747 ^ 8'd183);

assign xor_ln269_fu_608_p2 = (trunc_ln82_reg_742 ^ 8'd136);

assign xor_ln77_1_fu_435_p2 = (trunc_ln77_6_fu_425_p1 ^ trunc_ln77_5_fu_421_p1);

assign xor_ln77_2_fu_441_p2 = (trunc_ln77_4_fu_417_p1 ^ trunc_ln77_3_fu_413_p1);

assign zext_ln140_1_fu_488_p1 = b_fu_457_p4;

assign zext_ln140_2_fu_493_p1 = c_fu_467_p4;

assign zext_ln140_3_fu_498_p1 = d_fu_477_p2;

assign zext_ln140_fu_483_p1 = a_fu_447_p4;

assign zext_ln77_fu_366_p1 = i_0_reg_325;

endmodule //Blowfish_Encrypt
