#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("Blowfish_pary_s_address0", 5, hls_out, 0, "ap_memory", "mem_address", 1),
	Port_Property("Blowfish_pary_s_ce0", 1, hls_out, 0, "ap_memory", "mem_ce", 1),
	Port_Property("Blowfish_pary_s_q0", 32, hls_in, 0, "ap_memory", "mem_dout", 1),
	Port_Property("Blowfish_pary_s_address1", 5, hls_out, 0, "ap_memory", "MemPortADDR2", 1),
	Port_Property("Blowfish_pary_s_ce1", 1, hls_out, 0, "ap_memory", "MemPortCE2", 1),
	Port_Property("Blowfish_pary_s_q1", 32, hls_in, 0, "ap_memory", "MemPortDOUT2", 1),
	Port_Property("Blowfish_sbox_s_address0", 10, hls_out, 1, "ap_memory", "mem_address", 1),
	Port_Property("Blowfish_sbox_s_ce0", 1, hls_out, 1, "ap_memory", "mem_ce", 1),
	Port_Property("Blowfish_sbox_s_q0", 32, hls_in, 1, "ap_memory", "mem_dout", 1),
	Port_Property("Blowfish_sbox_s_address1", 10, hls_out, 1, "ap_memory", "MemPortADDR2", 1),
	Port_Property("Blowfish_sbox_s_ce1", 1, hls_out, 1, "ap_memory", "MemPortCE2", 1),
	Port_Property("Blowfish_sbox_s_q1", 32, hls_in, 1, "ap_memory", "MemPortDOUT2", 1),
	Port_Property("left_r_i", 32, hls_in, 2, "ap_ovld", "in_data", 1),
	Port_Property("left_r_o", 32, hls_out, 2, "ap_ovld", "out_data", 1),
	Port_Property("left_r_o_ap_vld", 1, hls_out, 2, "ap_ovld", "out_vld", 1),
	Port_Property("right_r_i", 32, hls_in, 3, "ap_ovld", "in_data", 1),
	Port_Property("right_r_o", 32, hls_out, 3, "ap_ovld", "out_data", 1),
	Port_Property("right_r_o_ap_vld", 1, hls_out, 3, "ap_ovld", "out_vld", 1),
};
const char* HLS_Design_Meta::dut_name = "Blowfish::EncryptBlock";
