// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "aes_decrypt.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic aes_decrypt::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic aes_decrypt::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<9> aes_decrypt::ap_ST_fsm_state1 = "1";
const sc_lv<9> aes_decrypt::ap_ST_fsm_state2 = "10";
const sc_lv<9> aes_decrypt::ap_ST_fsm_state3 = "100";
const sc_lv<9> aes_decrypt::ap_ST_fsm_state4 = "1000";
const sc_lv<9> aes_decrypt::ap_ST_fsm_state5 = "10000";
const sc_lv<9> aes_decrypt::ap_ST_fsm_state6 = "100000";
const sc_lv<9> aes_decrypt::ap_ST_fsm_state7 = "1000000";
const sc_lv<9> aes_decrypt::ap_ST_fsm_state8 = "10000000";
const sc_lv<9> aes_decrypt::ap_ST_fsm_state9 = "100000000";
const sc_lv<32> aes_decrypt::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> aes_decrypt::ap_const_lv32_1 = "1";
const sc_lv<1> aes_decrypt::ap_const_lv1_0 = "0";
const sc_lv<32> aes_decrypt::ap_const_lv32_2 = "10";
const sc_lv<32> aes_decrypt::ap_const_lv32_6 = "110";
const sc_lv<32> aes_decrypt::ap_const_lv32_7 = "111";
const sc_lv<3> aes_decrypt::ap_const_lv3_0 = "000";
const sc_lv<1> aes_decrypt::ap_const_lv1_1 = "1";
const sc_lv<32> aes_decrypt::ap_const_lv32_5 = "101";
const sc_lv<32> aes_decrypt::ap_const_lv32_8 = "1000";
const sc_lv<32> aes_decrypt::ap_const_lv32_4 = "100";
const sc_lv<32> aes_decrypt::ap_const_lv32_3 = "11";
const sc_lv<3> aes_decrypt::ap_const_lv3_4 = "100";
const sc_lv<3> aes_decrypt::ap_const_lv3_1 = "1";
const sc_lv<2> aes_decrypt::ap_const_lv2_0 = "00";
const bool aes_decrypt::ap_const_boolean_1 = true;

aes_decrypt::aes_decrypt(sc_module_name name) : sc_module(name), mVcdFile(0) {
    expandedKey_U = new aes_decrypt_expanbkb("expandedKey_U");
    expandedKey_U->clk(ap_clk);
    expandedKey_U->reset(ap_rst);
    expandedKey_U->address0(expandedKey_address0);
    expandedKey_U->ce0(expandedKey_ce0);
    expandedKey_U->we0(expandedKey_we0);
    expandedKey_U->d0(grp_expandKey_fu_257_expandedKey_d0);
    expandedKey_U->q0(expandedKey_q0);
    expandedKey_U->address1(expandedKey_address1);
    expandedKey_U->ce1(expandedKey_ce1);
    expandedKey_U->we1(expandedKey_we1);
    expandedKey_U->d1(grp_expandKey_fu_257_expandedKey_d1);
    expandedKey_U->q1(expandedKey_q1);
    block_U = new aes_decrypt_block("block_U");
    block_U->clk(ap_clk);
    block_U->reset(ap_rst);
    block_U->address0(block_address0);
    block_U->ce0(block_ce0);
    block_U->we0(block_we0);
    block_U->d0(block_d0);
    block_U->q0(block_q0);
    block_U->address1(grp_aes_invMain_fu_249_state_address1);
    block_U->ce1(block_ce1);
    block_U->we1(block_we1);
    block_U->d1(grp_aes_invMain_fu_249_state_d1);
    block_U->q1(block_q1);
    grp_aes_invMain_fu_249 = new aes_invMain("grp_aes_invMain_fu_249");
    grp_aes_invMain_fu_249->ap_clk(ap_clk);
    grp_aes_invMain_fu_249->ap_rst(ap_rst);
    grp_aes_invMain_fu_249->ap_start(grp_aes_invMain_fu_249_ap_start);
    grp_aes_invMain_fu_249->ap_done(grp_aes_invMain_fu_249_ap_done);
    grp_aes_invMain_fu_249->ap_idle(grp_aes_invMain_fu_249_ap_idle);
    grp_aes_invMain_fu_249->ap_ready(grp_aes_invMain_fu_249_ap_ready);
    grp_aes_invMain_fu_249->state_address0(grp_aes_invMain_fu_249_state_address0);
    grp_aes_invMain_fu_249->state_ce0(grp_aes_invMain_fu_249_state_ce0);
    grp_aes_invMain_fu_249->state_we0(grp_aes_invMain_fu_249_state_we0);
    grp_aes_invMain_fu_249->state_d0(grp_aes_invMain_fu_249_state_d0);
    grp_aes_invMain_fu_249->state_q0(block_q0);
    grp_aes_invMain_fu_249->state_address1(grp_aes_invMain_fu_249_state_address1);
    grp_aes_invMain_fu_249->state_ce1(grp_aes_invMain_fu_249_state_ce1);
    grp_aes_invMain_fu_249->state_we1(grp_aes_invMain_fu_249_state_we1);
    grp_aes_invMain_fu_249->state_d1(grp_aes_invMain_fu_249_state_d1);
    grp_aes_invMain_fu_249->state_q1(block_q1);
    grp_aes_invMain_fu_249->expandedKey_address0(grp_aes_invMain_fu_249_expandedKey_address0);
    grp_aes_invMain_fu_249->expandedKey_ce0(grp_aes_invMain_fu_249_expandedKey_ce0);
    grp_aes_invMain_fu_249->expandedKey_q0(expandedKey_q0);
    grp_aes_invMain_fu_249->expandedKey_address1(grp_aes_invMain_fu_249_expandedKey_address1);
    grp_aes_invMain_fu_249->expandedKey_ce1(grp_aes_invMain_fu_249_expandedKey_ce1);
    grp_aes_invMain_fu_249->expandedKey_q1(expandedKey_q1);
    grp_expandKey_fu_257 = new expandKey("grp_expandKey_fu_257");
    grp_expandKey_fu_257->ap_clk(ap_clk);
    grp_expandKey_fu_257->ap_rst(ap_rst);
    grp_expandKey_fu_257->ap_start(grp_expandKey_fu_257_ap_start);
    grp_expandKey_fu_257->ap_done(grp_expandKey_fu_257_ap_done);
    grp_expandKey_fu_257->ap_idle(grp_expandKey_fu_257_ap_idle);
    grp_expandKey_fu_257->ap_ready(grp_expandKey_fu_257_ap_ready);
    grp_expandKey_fu_257->expandedKey_address0(grp_expandKey_fu_257_expandedKey_address0);
    grp_expandKey_fu_257->expandedKey_ce0(grp_expandKey_fu_257_expandedKey_ce0);
    grp_expandKey_fu_257->expandedKey_we0(grp_expandKey_fu_257_expandedKey_we0);
    grp_expandKey_fu_257->expandedKey_d0(grp_expandKey_fu_257_expandedKey_d0);
    grp_expandKey_fu_257->expandedKey_q0(expandedKey_q0);
    grp_expandKey_fu_257->expandedKey_address1(grp_expandKey_fu_257_expandedKey_address1);
    grp_expandKey_fu_257->expandedKey_ce1(grp_expandKey_fu_257_expandedKey_ce1);
    grp_expandKey_fu_257->expandedKey_we1(grp_expandKey_fu_257_expandedKey_we1);
    grp_expandKey_fu_257->expandedKey_d1(grp_expandKey_fu_257_expandedKey_d1);
    grp_expandKey_fu_257->expandedKey_q1(expandedKey_q1);
    grp_expandKey_fu_257->key_address0(grp_expandKey_fu_257_key_address0);
    grp_expandKey_fu_257->key_ce0(grp_expandKey_fu_257_key_ce0);
    grp_expandKey_fu_257->key_q0(key_q0);
    decrypt_dut_mux_1cud_U51 = new decrypt_dut_mux_1cud<1,1,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,4,8>("decrypt_dut_mux_1cud_U51");
    decrypt_dut_mux_1cud_U51->din0(input_0_read);
    decrypt_dut_mux_1cud_U51->din1(input_1_read);
    decrypt_dut_mux_1cud_U51->din2(input_2_read);
    decrypt_dut_mux_1cud_U51->din3(input_3_read);
    decrypt_dut_mux_1cud_U51->din4(input_4_read);
    decrypt_dut_mux_1cud_U51->din5(input_5_read);
    decrypt_dut_mux_1cud_U51->din6(input_6_read);
    decrypt_dut_mux_1cud_U51->din7(input_7_read);
    decrypt_dut_mux_1cud_U51->din8(input_8_read);
    decrypt_dut_mux_1cud_U51->din9(input_9_read);
    decrypt_dut_mux_1cud_U51->din10(input_10_read);
    decrypt_dut_mux_1cud_U51->din11(input_11_read);
    decrypt_dut_mux_1cud_U51->din12(input_12_read);
    decrypt_dut_mux_1cud_U51->din13(input_13_read);
    decrypt_dut_mux_1cud_U51->din14(input_14_read);
    decrypt_dut_mux_1cud_U51->din15(input_15_read);
    decrypt_dut_mux_1cud_U51->din16(tmp_fu_317_p17);
    decrypt_dut_mux_1cud_U51->dout(tmp_fu_317_p18);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln77_1_fu_352_p2);
    sensitive << ( zext_ln72_reg_517 );
    sensitive << ( shl_ln77_1_fu_344_p3 );

    SC_METHOD(thread_add_ln93_1_fu_428_p2);
    sensitive << ( shl_ln1_reg_556 );
    sensitive << ( zext_ln91_fu_390_p1 );

    SC_METHOD(thread_add_ln93_fu_418_p2);
    sensitive << ( zext_ln88_reg_543 );
    sensitive << ( shl_ln93_1_fu_410_p3 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln88_fu_366_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln88_fu_366_p2 );

    SC_METHOD(thread_block_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( grp_aes_invMain_fu_249_state_address0 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( zext_ln77_fu_357_p1 );
    sensitive << ( zext_ln93_fu_423_p1 );

    SC_METHOD(thread_block_ce0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( grp_aes_invMain_fu_249_state_ce0 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_block_ce1);
    sensitive << ( grp_aes_invMain_fu_249_state_ce1 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_block_d0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( grp_aes_invMain_fu_249_state_d0 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( tmp_fu_317_p18 );

    SC_METHOD(thread_block_we0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( grp_aes_invMain_fu_249_state_we0 );
    sensitive << ( icmp_ln75_fu_300_p2 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_block_we1);
    sensitive << ( grp_aes_invMain_fu_249_state_we1 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_expandedKey_address0);
    sensitive << ( grp_aes_invMain_fu_249_expandedKey_address0 );
    sensitive << ( grp_expandKey_fu_257_expandedKey_address0 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_expandedKey_address1);
    sensitive << ( grp_aes_invMain_fu_249_expandedKey_address1 );
    sensitive << ( grp_expandKey_fu_257_expandedKey_address1 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_expandedKey_ce0);
    sensitive << ( grp_aes_invMain_fu_249_expandedKey_ce0 );
    sensitive << ( grp_expandKey_fu_257_expandedKey_ce0 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_expandedKey_ce1);
    sensitive << ( grp_aes_invMain_fu_249_expandedKey_ce1 );
    sensitive << ( grp_expandKey_fu_257_expandedKey_ce1 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_expandedKey_we0);
    sensitive << ( grp_expandKey_fu_257_expandedKey_we0 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_expandedKey_we1);
    sensitive << ( grp_expandKey_fu_257_expandedKey_we1 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_grp_aes_invMain_fu_249_ap_start);
    sensitive << ( grp_aes_invMain_fu_249_ap_start_reg );

    SC_METHOD(thread_grp_expandKey_fu_257_ap_start);
    sensitive << ( grp_expandKey_fu_257_ap_start_reg );

    SC_METHOD(thread_i_2_fu_372_p2);
    sensitive << ( i_1_reg_227 );

    SC_METHOD(thread_i_fu_278_p2);
    sensitive << ( i_0_reg_205 );

    SC_METHOD(thread_icmp_ln72_fu_272_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_0_reg_205 );

    SC_METHOD(thread_icmp_ln75_fu_300_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( j_0_reg_216 );

    SC_METHOD(thread_icmp_ln88_fu_366_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( i_1_reg_227 );

    SC_METHOD(thread_icmp_ln91_fu_394_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( j_1_reg_238 );

    SC_METHOD(thread_j_2_fu_400_p2);
    sensitive << ( j_1_reg_238 );

    SC_METHOD(thread_j_fu_306_p2);
    sensitive << ( j_0_reg_216 );

    SC_METHOD(thread_key_address0);
    sensitive << ( grp_expandKey_fu_257_key_address0 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_key_ce0);
    sensitive << ( grp_expandKey_fu_257_key_ce0 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_output_r_address0);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( zext_ln93_1_fu_433_p1 );

    SC_METHOD(thread_output_r_ce0);
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_output_r_d0);
    sensitive << ( block_q0 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_output_r_we0);
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_shl_ln1_fu_382_p3);
    sensitive << ( trunc_ln93_fu_378_p1 );

    SC_METHOD(thread_shl_ln77_1_fu_344_p3);
    sensitive << ( trunc_ln77_1_fu_340_p1 );

    SC_METHOD(thread_shl_ln93_1_fu_410_p3);
    sensitive << ( trunc_ln93_1_fu_406_p1 );

    SC_METHOD(thread_shl_ln_fu_288_p3);
    sensitive << ( trunc_ln77_fu_284_p1 );

    SC_METHOD(thread_tmp_fu_317_p17);
    sensitive << ( shl_ln_reg_530 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( zext_ln75_fu_296_p1 );

    SC_METHOD(thread_trunc_ln77_1_fu_340_p1);
    sensitive << ( j_0_reg_216 );

    SC_METHOD(thread_trunc_ln77_fu_284_p1);
    sensitive << ( i_0_reg_205 );

    SC_METHOD(thread_trunc_ln93_1_fu_406_p1);
    sensitive << ( j_1_reg_238 );

    SC_METHOD(thread_trunc_ln93_fu_378_p1);
    sensitive << ( i_1_reg_227 );

    SC_METHOD(thread_zext_ln72_fu_268_p1);
    sensitive << ( i_0_reg_205 );

    SC_METHOD(thread_zext_ln75_fu_296_p1);
    sensitive << ( j_0_reg_216 );

    SC_METHOD(thread_zext_ln77_fu_357_p1);
    sensitive << ( add_ln77_1_fu_352_p2 );

    SC_METHOD(thread_zext_ln88_fu_362_p1);
    sensitive << ( i_1_reg_227 );

    SC_METHOD(thread_zext_ln91_fu_390_p1);
    sensitive << ( j_1_reg_238 );

    SC_METHOD(thread_zext_ln93_1_fu_433_p1);
    sensitive << ( add_ln93_1_reg_574 );

    SC_METHOD(thread_zext_ln93_fu_423_p1);
    sensitive << ( add_ln93_fu_418_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln72_fu_272_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln88_fu_366_p2 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln91_fu_394_p2 );
    sensitive << ( grp_aes_invMain_fu_249_ap_done );
    sensitive << ( grp_expandKey_fu_257_ap_done );
    sensitive << ( icmp_ln75_fu_300_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state4 );

    ap_CS_fsm = "000000001";
    grp_aes_invMain_fu_249_ap_start_reg = SC_LOGIC_0;
    grp_expandKey_fu_257_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "aes_decrypt_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, input_0_read, "(port)input_0_read");
    sc_trace(mVcdFile, input_1_read, "(port)input_1_read");
    sc_trace(mVcdFile, input_2_read, "(port)input_2_read");
    sc_trace(mVcdFile, input_3_read, "(port)input_3_read");
    sc_trace(mVcdFile, input_4_read, "(port)input_4_read");
    sc_trace(mVcdFile, input_5_read, "(port)input_5_read");
    sc_trace(mVcdFile, input_6_read, "(port)input_6_read");
    sc_trace(mVcdFile, input_7_read, "(port)input_7_read");
    sc_trace(mVcdFile, input_8_read, "(port)input_8_read");
    sc_trace(mVcdFile, input_9_read, "(port)input_9_read");
    sc_trace(mVcdFile, input_10_read, "(port)input_10_read");
    sc_trace(mVcdFile, input_11_read, "(port)input_11_read");
    sc_trace(mVcdFile, input_12_read, "(port)input_12_read");
    sc_trace(mVcdFile, input_13_read, "(port)input_13_read");
    sc_trace(mVcdFile, input_14_read, "(port)input_14_read");
    sc_trace(mVcdFile, input_15_read, "(port)input_15_read");
    sc_trace(mVcdFile, output_r_address0, "(port)output_r_address0");
    sc_trace(mVcdFile, output_r_ce0, "(port)output_r_ce0");
    sc_trace(mVcdFile, output_r_we0, "(port)output_r_we0");
    sc_trace(mVcdFile, output_r_d0, "(port)output_r_d0");
    sc_trace(mVcdFile, key_address0, "(port)key_address0");
    sc_trace(mVcdFile, key_ce0, "(port)key_ce0");
    sc_trace(mVcdFile, key_q0, "(port)key_q0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, zext_ln72_fu_268_p1, "zext_ln72_fu_268_p1");
    sc_trace(mVcdFile, zext_ln72_reg_517, "zext_ln72_reg_517");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, i_fu_278_p2, "i_fu_278_p2");
    sc_trace(mVcdFile, i_reg_525, "i_reg_525");
    sc_trace(mVcdFile, shl_ln_fu_288_p3, "shl_ln_fu_288_p3");
    sc_trace(mVcdFile, shl_ln_reg_530, "shl_ln_reg_530");
    sc_trace(mVcdFile, icmp_ln72_fu_272_p2, "icmp_ln72_fu_272_p2");
    sc_trace(mVcdFile, j_fu_306_p2, "j_fu_306_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, zext_ln88_fu_362_p1, "zext_ln88_fu_362_p1");
    sc_trace(mVcdFile, zext_ln88_reg_543, "zext_ln88_reg_543");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, i_2_fu_372_p2, "i_2_fu_372_p2");
    sc_trace(mVcdFile, i_2_reg_551, "i_2_reg_551");
    sc_trace(mVcdFile, shl_ln1_fu_382_p3, "shl_ln1_fu_382_p3");
    sc_trace(mVcdFile, shl_ln1_reg_556, "shl_ln1_reg_556");
    sc_trace(mVcdFile, icmp_ln88_fu_366_p2, "icmp_ln88_fu_366_p2");
    sc_trace(mVcdFile, j_2_fu_400_p2, "j_2_fu_400_p2");
    sc_trace(mVcdFile, j_2_reg_564, "j_2_reg_564");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, icmp_ln91_fu_394_p2, "icmp_ln91_fu_394_p2");
    sc_trace(mVcdFile, add_ln93_1_fu_428_p2, "add_ln93_1_fu_428_p2");
    sc_trace(mVcdFile, add_ln93_1_reg_574, "add_ln93_1_reg_574");
    sc_trace(mVcdFile, expandedKey_address0, "expandedKey_address0");
    sc_trace(mVcdFile, expandedKey_ce0, "expandedKey_ce0");
    sc_trace(mVcdFile, expandedKey_we0, "expandedKey_we0");
    sc_trace(mVcdFile, expandedKey_q0, "expandedKey_q0");
    sc_trace(mVcdFile, expandedKey_address1, "expandedKey_address1");
    sc_trace(mVcdFile, expandedKey_ce1, "expandedKey_ce1");
    sc_trace(mVcdFile, expandedKey_we1, "expandedKey_we1");
    sc_trace(mVcdFile, expandedKey_q1, "expandedKey_q1");
    sc_trace(mVcdFile, block_address0, "block_address0");
    sc_trace(mVcdFile, block_ce0, "block_ce0");
    sc_trace(mVcdFile, block_we0, "block_we0");
    sc_trace(mVcdFile, block_d0, "block_d0");
    sc_trace(mVcdFile, block_q0, "block_q0");
    sc_trace(mVcdFile, block_ce1, "block_ce1");
    sc_trace(mVcdFile, block_we1, "block_we1");
    sc_trace(mVcdFile, block_q1, "block_q1");
    sc_trace(mVcdFile, grp_aes_invMain_fu_249_ap_start, "grp_aes_invMain_fu_249_ap_start");
    sc_trace(mVcdFile, grp_aes_invMain_fu_249_ap_done, "grp_aes_invMain_fu_249_ap_done");
    sc_trace(mVcdFile, grp_aes_invMain_fu_249_ap_idle, "grp_aes_invMain_fu_249_ap_idle");
    sc_trace(mVcdFile, grp_aes_invMain_fu_249_ap_ready, "grp_aes_invMain_fu_249_ap_ready");
    sc_trace(mVcdFile, grp_aes_invMain_fu_249_state_address0, "grp_aes_invMain_fu_249_state_address0");
    sc_trace(mVcdFile, grp_aes_invMain_fu_249_state_ce0, "grp_aes_invMain_fu_249_state_ce0");
    sc_trace(mVcdFile, grp_aes_invMain_fu_249_state_we0, "grp_aes_invMain_fu_249_state_we0");
    sc_trace(mVcdFile, grp_aes_invMain_fu_249_state_d0, "grp_aes_invMain_fu_249_state_d0");
    sc_trace(mVcdFile, grp_aes_invMain_fu_249_state_address1, "grp_aes_invMain_fu_249_state_address1");
    sc_trace(mVcdFile, grp_aes_invMain_fu_249_state_ce1, "grp_aes_invMain_fu_249_state_ce1");
    sc_trace(mVcdFile, grp_aes_invMain_fu_249_state_we1, "grp_aes_invMain_fu_249_state_we1");
    sc_trace(mVcdFile, grp_aes_invMain_fu_249_state_d1, "grp_aes_invMain_fu_249_state_d1");
    sc_trace(mVcdFile, grp_aes_invMain_fu_249_expandedKey_address0, "grp_aes_invMain_fu_249_expandedKey_address0");
    sc_trace(mVcdFile, grp_aes_invMain_fu_249_expandedKey_ce0, "grp_aes_invMain_fu_249_expandedKey_ce0");
    sc_trace(mVcdFile, grp_aes_invMain_fu_249_expandedKey_address1, "grp_aes_invMain_fu_249_expandedKey_address1");
    sc_trace(mVcdFile, grp_aes_invMain_fu_249_expandedKey_ce1, "grp_aes_invMain_fu_249_expandedKey_ce1");
    sc_trace(mVcdFile, grp_expandKey_fu_257_ap_start, "grp_expandKey_fu_257_ap_start");
    sc_trace(mVcdFile, grp_expandKey_fu_257_ap_done, "grp_expandKey_fu_257_ap_done");
    sc_trace(mVcdFile, grp_expandKey_fu_257_ap_idle, "grp_expandKey_fu_257_ap_idle");
    sc_trace(mVcdFile, grp_expandKey_fu_257_ap_ready, "grp_expandKey_fu_257_ap_ready");
    sc_trace(mVcdFile, grp_expandKey_fu_257_expandedKey_address0, "grp_expandKey_fu_257_expandedKey_address0");
    sc_trace(mVcdFile, grp_expandKey_fu_257_expandedKey_ce0, "grp_expandKey_fu_257_expandedKey_ce0");
    sc_trace(mVcdFile, grp_expandKey_fu_257_expandedKey_we0, "grp_expandKey_fu_257_expandedKey_we0");
    sc_trace(mVcdFile, grp_expandKey_fu_257_expandedKey_d0, "grp_expandKey_fu_257_expandedKey_d0");
    sc_trace(mVcdFile, grp_expandKey_fu_257_expandedKey_address1, "grp_expandKey_fu_257_expandedKey_address1");
    sc_trace(mVcdFile, grp_expandKey_fu_257_expandedKey_ce1, "grp_expandKey_fu_257_expandedKey_ce1");
    sc_trace(mVcdFile, grp_expandKey_fu_257_expandedKey_we1, "grp_expandKey_fu_257_expandedKey_we1");
    sc_trace(mVcdFile, grp_expandKey_fu_257_expandedKey_d1, "grp_expandKey_fu_257_expandedKey_d1");
    sc_trace(mVcdFile, grp_expandKey_fu_257_key_address0, "grp_expandKey_fu_257_key_address0");
    sc_trace(mVcdFile, grp_expandKey_fu_257_key_ce0, "grp_expandKey_fu_257_key_ce0");
    sc_trace(mVcdFile, i_0_reg_205, "i_0_reg_205");
    sc_trace(mVcdFile, icmp_ln75_fu_300_p2, "icmp_ln75_fu_300_p2");
    sc_trace(mVcdFile, j_0_reg_216, "j_0_reg_216");
    sc_trace(mVcdFile, i_1_reg_227, "i_1_reg_227");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, j_1_reg_238, "j_1_reg_238");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, grp_aes_invMain_fu_249_ap_start_reg, "grp_aes_invMain_fu_249_ap_start_reg");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, grp_expandKey_fu_257_ap_start_reg, "grp_expandKey_fu_257_ap_start_reg");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, zext_ln77_fu_357_p1, "zext_ln77_fu_357_p1");
    sc_trace(mVcdFile, zext_ln93_fu_423_p1, "zext_ln93_fu_423_p1");
    sc_trace(mVcdFile, zext_ln93_1_fu_433_p1, "zext_ln93_1_fu_433_p1");
    sc_trace(mVcdFile, tmp_fu_317_p18, "tmp_fu_317_p18");
    sc_trace(mVcdFile, trunc_ln77_fu_284_p1, "trunc_ln77_fu_284_p1");
    sc_trace(mVcdFile, zext_ln75_fu_296_p1, "zext_ln75_fu_296_p1");
    sc_trace(mVcdFile, tmp_fu_317_p17, "tmp_fu_317_p17");
    sc_trace(mVcdFile, trunc_ln77_1_fu_340_p1, "trunc_ln77_1_fu_340_p1");
    sc_trace(mVcdFile, shl_ln77_1_fu_344_p3, "shl_ln77_1_fu_344_p3");
    sc_trace(mVcdFile, add_ln77_1_fu_352_p2, "add_ln77_1_fu_352_p2");
    sc_trace(mVcdFile, trunc_ln93_fu_378_p1, "trunc_ln93_fu_378_p1");
    sc_trace(mVcdFile, trunc_ln93_1_fu_406_p1, "trunc_ln93_1_fu_406_p1");
    sc_trace(mVcdFile, shl_ln93_1_fu_410_p3, "shl_ln93_1_fu_410_p3");
    sc_trace(mVcdFile, add_ln93_fu_418_p2, "add_ln93_fu_418_p2");
    sc_trace(mVcdFile, zext_ln91_fu_390_p1, "zext_ln91_fu_390_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

aes_decrypt::~aes_decrypt() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete expandedKey_U;
    delete block_U;
    delete grp_aes_invMain_fu_249;
    delete grp_expandKey_fu_257;
    delete decrypt_dut_mux_1cud_U51;
}

void aes_decrypt::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_aes_invMain_fu_249_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
            grp_aes_invMain_fu_249_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_aes_invMain_fu_249_ap_ready.read())) {
            grp_aes_invMain_fu_249_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_expandKey_fu_257_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
             esl_seteq<1,1,1>(icmp_ln72_fu_272_p2.read(), ap_const_lv1_1))) {
            grp_expandKey_fu_257_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_expandKey_fu_257_ap_ready.read())) {
            grp_expandKey_fu_257_ap_start_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln75_fu_300_p2.read(), ap_const_lv1_1))) {
        i_0_reg_205 = i_reg_525.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_0_reg_205 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(icmp_ln91_fu_394_p2.read(), ap_const_lv1_1))) {
        i_1_reg_227 = i_2_reg_551.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(grp_aes_invMain_fu_249_ap_done.read(), ap_const_logic_1))) {
        i_1_reg_227 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln72_fu_272_p2.read(), ap_const_lv1_0))) {
        j_0_reg_216 = ap_const_lv3_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln75_fu_300_p2.read()))) {
        j_0_reg_216 = j_fu_306_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln88_fu_366_p2.read()))) {
        j_1_reg_238 = ap_const_lv3_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        j_1_reg_238 = j_2_reg_564.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln91_fu_394_p2.read()))) {
        add_ln93_1_reg_574 = add_ln93_1_fu_428_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        i_2_reg_551 = i_2_fu_372_p2.read();
        zext_ln88_reg_543 = zext_ln88_fu_362_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_reg_525 = i_fu_278_p2.read();
        zext_ln72_reg_517 = zext_ln72_fu_268_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        j_2_reg_564 = j_2_fu_400_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln88_fu_366_p2.read()))) {
        shl_ln1_reg_556 = shl_ln1_fu_382_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln72_fu_272_p2.read(), ap_const_lv1_0))) {
        shl_ln_reg_530 = shl_ln_fu_288_p3.read();
    }
}

void aes_decrypt::thread_add_ln77_1_fu_352_p2() {
    add_ln77_1_fu_352_p2 = (!zext_ln72_reg_517.read().is_01() || !shl_ln77_1_fu_344_p3.read().is_01())? sc_lv<4>(): (sc_biguint<4>(zext_ln72_reg_517.read()) + sc_biguint<4>(shl_ln77_1_fu_344_p3.read()));
}

void aes_decrypt::thread_add_ln93_1_fu_428_p2() {
    add_ln93_1_fu_428_p2 = (!zext_ln91_fu_390_p1.read().is_01() || !shl_ln1_reg_556.read().is_01())? sc_lv<4>(): (sc_biguint<4>(zext_ln91_fu_390_p1.read()) + sc_biguint<4>(shl_ln1_reg_556.read()));
}

void aes_decrypt::thread_add_ln93_fu_418_p2() {
    add_ln93_fu_418_p2 = (!shl_ln93_1_fu_410_p3.read().is_01() || !zext_ln88_reg_543.read().is_01())? sc_lv<4>(): (sc_biguint<4>(shl_ln93_1_fu_410_p3.read()) + sc_biguint<4>(zext_ln88_reg_543.read()));
}

void aes_decrypt::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void aes_decrypt::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void aes_decrypt::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void aes_decrypt::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void aes_decrypt::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void aes_decrypt::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void aes_decrypt::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void aes_decrypt::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void aes_decrypt::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void aes_decrypt::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
          esl_seteq<1,1,1>(icmp_ln88_fu_366_p2.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void aes_decrypt::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void aes_decrypt::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(icmp_ln88_fu_366_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void aes_decrypt::thread_block_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        block_address0 =  (sc_lv<4>) (zext_ln93_fu_423_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        block_address0 =  (sc_lv<4>) (zext_ln77_fu_357_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        block_address0 = grp_aes_invMain_fu_249_state_address0.read();
    } else {
        block_address0 = "XXXX";
    }
}

void aes_decrypt::thread_block_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()))) {
        block_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        block_ce0 = grp_aes_invMain_fu_249_state_ce0.read();
    } else {
        block_ce0 = ap_const_logic_0;
    }
}

void aes_decrypt::thread_block_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        block_ce1 = grp_aes_invMain_fu_249_state_ce1.read();
    } else {
        block_ce1 = ap_const_logic_0;
    }
}

void aes_decrypt::thread_block_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        block_d0 = tmp_fu_317_p18.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        block_d0 = grp_aes_invMain_fu_249_state_d0.read();
    } else {
        block_d0 =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void aes_decrypt::thread_block_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln75_fu_300_p2.read()))) {
        block_we0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        block_we0 = grp_aes_invMain_fu_249_state_we0.read();
    } else {
        block_we0 = ap_const_logic_0;
    }
}

void aes_decrypt::thread_block_we1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        block_we1 = grp_aes_invMain_fu_249_state_we1.read();
    } else {
        block_we1 = ap_const_logic_0;
    }
}

void aes_decrypt::thread_expandedKey_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        expandedKey_address0 = grp_expandKey_fu_257_expandedKey_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        expandedKey_address0 = grp_aes_invMain_fu_249_expandedKey_address0.read();
    } else {
        expandedKey_address0 =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void aes_decrypt::thread_expandedKey_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        expandedKey_address1 = grp_expandKey_fu_257_expandedKey_address1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        expandedKey_address1 = grp_aes_invMain_fu_249_expandedKey_address1.read();
    } else {
        expandedKey_address1 =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void aes_decrypt::thread_expandedKey_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        expandedKey_ce0 = grp_expandKey_fu_257_expandedKey_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        expandedKey_ce0 = grp_aes_invMain_fu_249_expandedKey_ce0.read();
    } else {
        expandedKey_ce0 = ap_const_logic_0;
    }
}

void aes_decrypt::thread_expandedKey_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        expandedKey_ce1 = grp_expandKey_fu_257_expandedKey_ce1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        expandedKey_ce1 = grp_aes_invMain_fu_249_expandedKey_ce1.read();
    } else {
        expandedKey_ce1 = ap_const_logic_0;
    }
}

void aes_decrypt::thread_expandedKey_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        expandedKey_we0 = grp_expandKey_fu_257_expandedKey_we0.read();
    } else {
        expandedKey_we0 = ap_const_logic_0;
    }
}

void aes_decrypt::thread_expandedKey_we1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        expandedKey_we1 = grp_expandKey_fu_257_expandedKey_we1.read();
    } else {
        expandedKey_we1 = ap_const_logic_0;
    }
}

void aes_decrypt::thread_grp_aes_invMain_fu_249_ap_start() {
    grp_aes_invMain_fu_249_ap_start = grp_aes_invMain_fu_249_ap_start_reg.read();
}

void aes_decrypt::thread_grp_expandKey_fu_257_ap_start() {
    grp_expandKey_fu_257_ap_start = grp_expandKey_fu_257_ap_start_reg.read();
}

void aes_decrypt::thread_i_2_fu_372_p2() {
    i_2_fu_372_p2 = (!i_1_reg_227.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(i_1_reg_227.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void aes_decrypt::thread_i_fu_278_p2() {
    i_fu_278_p2 = (!i_0_reg_205.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(i_0_reg_205.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void aes_decrypt::thread_icmp_ln72_fu_272_p2() {
    icmp_ln72_fu_272_p2 = (!i_0_reg_205.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_205.read() == ap_const_lv3_4);
}

void aes_decrypt::thread_icmp_ln75_fu_300_p2() {
    icmp_ln75_fu_300_p2 = (!j_0_reg_216.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(j_0_reg_216.read() == ap_const_lv3_4);
}

void aes_decrypt::thread_icmp_ln88_fu_366_p2() {
    icmp_ln88_fu_366_p2 = (!i_1_reg_227.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(i_1_reg_227.read() == ap_const_lv3_4);
}

void aes_decrypt::thread_icmp_ln91_fu_394_p2() {
    icmp_ln91_fu_394_p2 = (!j_1_reg_238.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(j_1_reg_238.read() == ap_const_lv3_4);
}

void aes_decrypt::thread_j_2_fu_400_p2() {
    j_2_fu_400_p2 = (!j_1_reg_238.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(j_1_reg_238.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void aes_decrypt::thread_j_fu_306_p2() {
    j_fu_306_p2 = (!j_0_reg_216.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(j_0_reg_216.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void aes_decrypt::thread_key_address0() {
    key_address0 = grp_expandKey_fu_257_key_address0.read();
}

void aes_decrypt::thread_key_ce0() {
    key_ce0 = grp_expandKey_fu_257_key_ce0.read();
}

void aes_decrypt::thread_output_r_address0() {
    output_r_address0 =  (sc_lv<4>) (zext_ln93_1_fu_433_p1.read());
}

void aes_decrypt::thread_output_r_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        output_r_ce0 = ap_const_logic_1;
    } else {
        output_r_ce0 = ap_const_logic_0;
    }
}

void aes_decrypt::thread_output_r_d0() {
    output_r_d0 = block_q0.read();
}

void aes_decrypt::thread_output_r_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        output_r_we0 = ap_const_logic_1;
    } else {
        output_r_we0 = ap_const_logic_0;
    }
}

void aes_decrypt::thread_shl_ln1_fu_382_p3() {
    shl_ln1_fu_382_p3 = esl_concat<2,2>(trunc_ln93_fu_378_p1.read(), ap_const_lv2_0);
}

void aes_decrypt::thread_shl_ln77_1_fu_344_p3() {
    shl_ln77_1_fu_344_p3 = esl_concat<2,2>(trunc_ln77_1_fu_340_p1.read(), ap_const_lv2_0);
}

void aes_decrypt::thread_shl_ln93_1_fu_410_p3() {
    shl_ln93_1_fu_410_p3 = esl_concat<2,2>(trunc_ln93_1_fu_406_p1.read(), ap_const_lv2_0);
}

void aes_decrypt::thread_shl_ln_fu_288_p3() {
    shl_ln_fu_288_p3 = esl_concat<2,2>(trunc_ln77_fu_284_p1.read(), ap_const_lv2_0);
}

void aes_decrypt::thread_tmp_fu_317_p17() {
    tmp_fu_317_p17 = (!zext_ln75_fu_296_p1.read().is_01() || !shl_ln_reg_530.read().is_01())? sc_lv<4>(): (sc_biguint<4>(zext_ln75_fu_296_p1.read()) + sc_biguint<4>(shl_ln_reg_530.read()));
}

void aes_decrypt::thread_trunc_ln77_1_fu_340_p1() {
    trunc_ln77_1_fu_340_p1 = j_0_reg_216.read().range(2-1, 0);
}

void aes_decrypt::thread_trunc_ln77_fu_284_p1() {
    trunc_ln77_fu_284_p1 = i_0_reg_205.read().range(2-1, 0);
}

void aes_decrypt::thread_trunc_ln93_1_fu_406_p1() {
    trunc_ln93_1_fu_406_p1 = j_1_reg_238.read().range(2-1, 0);
}

void aes_decrypt::thread_trunc_ln93_fu_378_p1() {
    trunc_ln93_fu_378_p1 = i_1_reg_227.read().range(2-1, 0);
}

void aes_decrypt::thread_zext_ln72_fu_268_p1() {
    zext_ln72_fu_268_p1 = esl_zext<4,3>(i_0_reg_205.read());
}

void aes_decrypt::thread_zext_ln75_fu_296_p1() {
    zext_ln75_fu_296_p1 = esl_zext<4,3>(j_0_reg_216.read());
}

void aes_decrypt::thread_zext_ln77_fu_357_p1() {
    zext_ln77_fu_357_p1 = esl_zext<64,4>(add_ln77_1_fu_352_p2.read());
}

void aes_decrypt::thread_zext_ln88_fu_362_p1() {
    zext_ln88_fu_362_p1 = esl_zext<4,3>(i_1_reg_227.read());
}

void aes_decrypt::thread_zext_ln91_fu_390_p1() {
    zext_ln91_fu_390_p1 = esl_zext<4,3>(j_1_reg_238.read());
}

void aes_decrypt::thread_zext_ln93_1_fu_433_p1() {
    zext_ln93_1_fu_433_p1 = esl_zext<64,4>(add_ln93_1_reg_574.read());
}

void aes_decrypt::thread_zext_ln93_fu_423_p1() {
    zext_ln93_fu_423_p1 = esl_zext<64,4>(add_ln93_fu_418_p2.read());
}

void aes_decrypt::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln72_fu_272_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln75_fu_300_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(grp_expandKey_fu_257_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(grp_aes_invMain_fu_249_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(icmp_ln88_fu_366_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 128 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(icmp_ln91_fu_394_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else {
                ap_NS_fsm = ap_ST_fsm_state9;
            }
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<9>) ("XXXXXXXXX");
            break;
    }
}

}

